[package]
authors = ["Lana Ivina lanaconstanceives@gmail.com"]
description = 'Pallet for file signatures'
edition = '2018'
homepage = 'https://evercity.io'
license = 'Apache-2.0'
name = 'pallet-evercity-filesign'
readme = '../README.md'
repository = 'https://github.com/EvercityEcosystem/filesign'
version = '0.1.4'

[dependencies.fixed-hash]
version = "0.7"
default-features = false 

[dependencies.serde]
optional = true
features = ['derive']
version = '1.0.124'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']
[dev-dependencies.serde]
version = '1.0.119'
try-runtime = ['frame-support/try-runtime']

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
pallet-timestamp = { default-features = false, version = '3.0.0' }
sp-api = { default-features = false, version = '3.0.0' }
pallet-randomness-collective-flip = { default-features = false, version = '3.0.0' }

sp-io = { default-features = false, version = '3.0.0' }
# rand = { version = '0.8.4', features = ['js'] }
# uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen", "stdweb", "no_std"] }

[dev-dependencies]
sp-core = {  version = '3.0.0' }
# pallet-babe = { default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
    # 'uuid',
    'serde',
    'codec/std',
    'sp-api/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-timestamp/std',
    'pallet-randomness-collective-flip/std',
    # 'pallet-babe/std'
]